spring:
  application:
    name: notification-service
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  cassandra:
    keyspace-name: ${CASSANDRA_KEYSPACE_NAME}
    contact-points: ${CASSANDRA_CONTACT_POINTS}
    port: ${CASSANDRA_PORT}
    local-datacenter: ${CASSANDRA_LOCAL_DATACENTER}
    schema-action: create_if_not_exists

server:
  port: 8082

jwt:
  user:
    secret: ${USER_JWT_SECRET}
    access:
      expiration: ${USER_ACCESS_JWT_EXPIRATION}
    refresh:
      expiration: ${USER_REFRESH_JWT_EXPIRATION}



