version: '3.8'

services:
  # =========================
  # PostgreSQL
  # =========================
  postgres:
    image: postgres:latest
    container_name: evalink-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: evalink_db
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d evalink_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auth-network

  # =========================
  # Kafka кластер (KRaft)
  # =========================
  evalink-kafka-1:
    image: bitnami/kafka:latest
    container_name: evalink-kafka-1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=PVjHlx7ESeesq55jeB6Efw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@evalink-kafka-1:9091,2@evalink-kafka-2:9091,3@evalink-kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://evalink-kafka-1:9090,EXTERNAL://${HOSTNAME:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka1_data:/bitnami/kafka
    networks:
      - auth-network

  evalink-kafka-2:
    image: bitnami/kafka:latest
    container_name: evalink-kafka-2
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=PVjHlx7ESeesq55jeB6Efw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@evalink-kafka-1:9091,2@evalink-kafka-2:9091,3@evalink-kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://evalink-kafka-2:9090,EXTERNAL://${HOSTNAME:-localhost}:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka2_data:/bitnami/kafka
    networks:
      - auth-network

  evalink-kafka-3:
    image: bitnami/kafka:latest
    container_name: evalink-kafka-3
    ports:
      - "9096:9096"
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=PVjHlx7ESeesq55jeB6Efw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@evalink-kafka-1:9091,2@evalink-kafka-2:9091,3@evalink-kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://evalink-kafka-3:9090,EXTERNAL://${HOSTNAME:-localhost}:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka3_data:/bitnami/kafka
    networks:
      - auth-network

  # =========================
  # Redis
  # =========================
  redis:
    image: redis:latest
    container_name: evalink-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - auth-network

  # =========================
  # Loki
  # =========================
  loki:
    image: grafana/loki:2.9.0
    container_name: evalink-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - auth-network
    volumes:
      - loki_data:/loki

  # =========================
  # Promtail
  # =========================
  promtail:
    image: grafana/promtail:2.9.0
    container_name: evalink-promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /etc/localtime:/etc/localtime:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - auth-network
    depends_on:
      - loki

  # =========================
  # Grafana
  # =========================
  grafana:
    image: grafana/grafana:10.4.0
    container_name: evalink-grafana
    ports:
      - "3000:3000"
    networks:
      - auth-network
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki

# =========================
# Volumes
# =========================
volumes:
  postgres_data:
  kafka1_data:
  kafka2_data:
  kafka3_data:
  redis_data:
  loki_data:
  grafana_data:

# =========================
# Networks
# =========================
networks:
  auth-network:
    driver: bridge
